version: 2
jobs:
  test:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install yarn
          command: |
            curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.15.2
            export PATH=$HOME/.yarn/bin:$PATH
      - run: yarn install --offline --frozen-lockfile
      - run:
          # Helps to speed up some of the tests that we have
          name: Build packages
          command: yarn build
      - run:
          name: Run ci checks
          command: yarn ci-check
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"
      - store_test_results:
          path: reports
      - store_artifacts:
          path: reports

workflows:
  version: 2
  main:
    jobs:
      - test
